### ISSUE TITLE
Construcción de la ventana1 primera parte

### ISSUE THREAD

**Issue by Medina-Anderson** [Medina-Anderson/Clase9#1]
construir la venta1 y hacer el formulario para ingresar la información del cliente

**Comment by ghost** [comment]
Saludos voy a encargarme de esta funcionalidad.

**Comment by Medina-Anderson** [comment]
Listo, trabajo cumplido, por favor revisar el nuevo issue para hacer en ventana1.py el formulario de registro del usuario
